---
title: "country_specific_dataprep"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{country_specific_dataprep}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(STDataMGMT)
library(dplyr)
```

## Parameters
```{r}

# Asset Impact params

path_ar_data_raw <-
  r2dii.utils::path_dropbox_2dii(
    "ST_INPUTS",
    "ST_INPUTS_PRODUCTION",
    "AR-Company-Indicators_2022Q4.xlsx"
  )


# leave empty to use all countries
# countrycode::codelist %>%
#   filter(country.name.en == "Slovakia") %>%
#   dplyr::pull(.data$ecb)
country_filter <- c("SK") 

# only use assets with HQ in the selected countries
filter_hqs <- FALSE
# only use assets in the selected countries
filter_assets <- FALSE


# abcd  params ========================================
# start_year <- 2022 # defined in workflow.R
time_horizon <- 5
additional_year <- NULL
sector_list <- c("Automotive", "Power", "Oil&Gas", "Coal")
km_per_vehicle <- 15000



```



## Load Asset Impact data
```{r}
outputs_list <- prepare_asset_impact_data(ar_data_path = path_ar_data_raw)
DB_company_activities <- outputs_list[["company_activities"]]
DB_company_emissions <- outputs_list[["company_emissions"]]
```




## Prepare raw Asset Impact
```{r include=FALSE}
company_informations <- read_asset_resolution(path_ar_data_raw,
                                              sheet_name = "Company Information")
# check that company/country pairs are uniques
company_informations %>%
  dplyr::group_by(company_id, ald_location) %>%
  dplyr::summarise(nrows = dplyr::n()) %>%
  dplyr::ungroup() %>%
  assertr::verify(max(nrows) == 1)

DB_company_activities <- DB_company_activities %>%
  filter_countries_coverage(
    company_informations = company_informations,
    country_filter = country_filter,
    filter_hqs = filter_hqs,
    filter_assets = filter_assets
  )

DB_company_emissions <- DB_company_emissions %>%
  filter_countries_coverage(
    company_informations = company_informations,
    country_filter = country_filter,
    filter_hqs = filter_hqs,
    filter_assets = filter_assets
  )

```


```{r}
DB_company_activities %>%
  distinct(company_id, ald_location) %>%
  group_by(ald_location) %>%
  summarise(n = n()) %>%
  arrange(desc(n)) 
```


## Transform to ABCD

```{r}
abcd_stress_test_input <-
  prepare_abcd_data(
    company_activities = DB_company_activities,
    company_emissions = DB_company_emissions,
    scenarios_geographies = scenarios_geographies, # loaded from package
    start_year = start_year,
    time_horizon = time_horizon,
    additional_year = additional_year,
    km_per_vehicle = km_per_vehicle,
    sector_list = sector_list
  )

```



```{r}
abcd_stress_test_input %>% 
  distinct(company_name)
```


```{r}
abcd_stress_test_input %>%
  distinct(company_id, ald_sector, ald_business_unit) %>%
  group_by(ald_sector, ald_business_unit) %>%
  summarise(n = n()) %>%
  arrange(desc(n)) %>%
  print(n = Inf)
```


```{r}
abcd_stress_test_input %>%
  distinct(company_id, scenario_geography) %>%
  group_by(scenario_geography) %>%
  summarise(n = n()) %>%
  arrange(desc(n)) %>%
  print(n = Inf)
```

