---
title: "ticket_4_compare_company_names financial v abcd"
output: github_document
date: "2022-09-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages, echo=FALSE, message=FALSE}
devtools::load_all()
```

```{r load financial data, echo=FALSE}
financial_data_path <- r2dii.utils::path_dropbox_2dii("PortCheck", "00_Data", "07_AnalysisInputs", "ST_INPUTS_MASTER", "prewrangled_financial_data_stress_test.csv")

financial_data <- read.csv(financial_data_path)
```

```{r load stress test data, echo=FALSE}
abcd_full_path <- r2dii.utils::path_dropbox_2dii("PortCheck", "00_Data", "07_AnalysisInputs", "ST_INPUTS_MASTER", "abcd_stress_test_input.csv")

abcd_full <- read.csv(abcd_full_path)

```


#1.Count uniqe company_name in abcd_stress_test (42 500)
```{r filter company names abcd, echo=FALSE}
abcd_full_names <- abcd_full %>% dplyr::select(company_name) %>% unique()
```

```{r show dim}
dim(abcd_full_names)
```


#2.Count uniqe company_name in financial_data (50 492)
```{r filter company names, echo=FALSE}
financial_data_names <- financial_data %>% dplyr::select(company_name) %>% unique()
```

```{r show dim finance}
dim(financial_data_names)
```


#3.Match company names 

```{r match and show dim}
check <- dplyr::inner_join(abcd_full_names,financial_data_names, by = "company_name")

dim(check)
```

*It seems that mostly matching does not work bc company names slightly differ*
*e.g. Solvay SA (abcd_stress_test) is Solvay Sa (financial data)*
*e.g.Canada Pension Plan Investment Board is Canada Pension Plan Investment*
